# Generated by Django 5.0.4 on 2024-04-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_discription',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
    ]
