# Generated by Django 5.0.4 on 2024-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='banner',
            field=models.ImageField(default='', upload_to='banner_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=True, upload_to='profile'),
        ),
    ]
