# Generated by Django 5.0.4 on 2024-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='banner',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='Product/i_phone.webp', upload_to='Product'),
        ),
    ]
