# Generated by Django 5.0.4 on 2024-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='profile/profile-default.jpg', upload_to='Product'),
        ),
    ]
