# Generated by Django 5.0.4 on 2024-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='Product/i_phone.webp', upload_to='Product'),
        ),
    ]
