# Generated by Django 5.0.4 on 2024-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_productimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
