# Generated by Django 5.0.4 on 2024-04-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
